import React from 'react'
import { PublicLegalPage } from '../components/public/PublicPagePrimitives'

const Terms = () => (
  <PublicLegalPage
    title="Terms and Conditions - FarmEazy"
    description="These terms govern use of FarmEazy accounts, agricultural marketplace listings, products, services, payments, coins, support, and related platform features."
    noteTitle="Important platform terms"
    noteText="FarmEazy is a technology marketplace and facilitator. Product/service providers remain responsible for the goods or services they offer, subject to applicable law. By creating an account, users confirm that they have read and accepted these Terms and the Privacy Policy."
    sections={[
      { title: '1. Account and Consent', body: 'Users must provide accurate information, keep account credentials secure, and maintain only accounts they are authorized to use. Registration requires acceptance of these Terms and the Privacy Policy. FarmEazy may require identity, contact, vendor, bank, or other verification before marketplace features are enabled.' },
      { title: '2. Marketplace Listings', body: 'Sellers and service providers are responsible for accurate descriptions, lawful ownership or authority to sell/provide the listed item, availability, pricing, condition, photographs, documents, delivery/service commitments, and applicable permits or registrations. Listings must not contain unlawful, fraudulent, counterfeit, unsafe, misleading, or prohibited goods or services.' },
      { title: '3. Agricultural Products and Livestock', body: 'FarmEazy may support agricultural inputs, produce, machinery, equipment, livestock/cattle and other lawful agricultural products. Sellers must disclose material information relevant to the category, comply with animal-welfare, transport, veterinary, food-safety, weights-and-measures, taxation, and other applicable requirements, and must not misrepresent health, breed, age, ownership, condition, or origin.' },
      { title: '4. Agricultural Services', body: 'Service providers are responsible for the capability, availability, equipment condition, operator/driver arrangements, safety, transport, working hours, and lawful performance of posted services. Customers are responsible for providing accurate service location, timing, work requirements, farm/crop context when supplied, and access information. A booking becomes binding according to the status shown by FarmEazy and the applicable cancellation rules.' },
      { title: '5. Availability and Booking', body: 'Availability, geographic eligibility, capacity, time windows, and booking conflicts are determined by FarmEazy server-side controls. Users must not attempt to bypass availability, capacity, geographic, identity, or authorization controls. Concurrent booking attempts may result in only the available capacity being accepted.' },
      { title: '6. Prices, Taxes, Fees and Discounts', body: 'Checkout may include item/service charges, transport, driver/operator charges, platform fees, taxes, discounts, coins, and other disclosed charges. Final calculations are determined by FarmEazy server-side rules. Promotional discounts are subject to their published conditions, validity period, usage limits, eligibility, and applicable product/service scope.' },
      { title: '7. Coupons', body: 'Coupons are promotional benefits created by authorized FarmEazy administrators. A coupon may have a minimum order value, maximum discount, expiry, usage limit, per-user limit, or product/service scope. FarmEazy may reject a coupon that is invalid, expired, already exhausted, or not applicable to the transaction. Coupon discounts are not transferable or redeemable for cash unless expressly stated.' },
      { title: '8. Payments', body: 'Where a payment gateway is available, FarmEazy uses the configured payment provider and server-side verification. Users must not submit false payment information or attempt to replay, manipulate, or bypass payment verification. Direct/off-platform payments, where enabled, are transactions between the relevant parties and may not represent money received or verified by FarmEazy.' },
      { title: '9. FarmEazy Coins', body: 'Coins are a platform loyalty/reward balance, not cash or a bank deposit. Coin use is subject to current FarmEazy rules and available balance. Transactions must be completed through authorized platform flows. Promotional coin-back rewards, including any stated percentage reward, are issued only when the transaction qualifies and are recorded against the relevant transaction. FarmEazy may correct balances resulting from fraud, duplicate processing, technical errors, chargebacks, refunds, or unauthorized use.' },
      { title: '10. Cancellations, Completion and Adjustments', body: 'Cancellation, completion, refund, price-adjustment, and payout behavior follows the applicable transaction workflow shown in the platform. For agricultural services, a provider may be permitted to submit a limited number of post-completion price adjustments where the actual work materially differs from the initial quote. Such adjustments are subject to authorization, audit history, and payment state.' },
      { title: '11. Delivery, Transport and Service Location', body: 'Users must provide accurate delivery/service addresses and relevant access information. Transport, pickup, drop, mobilization, and distance-based charges may apply where disclosed. FarmEazy may restrict transactions by geographic coverage, delivery availability, service radius, administrative area, or other operational constraints.' },
      { title: '12. Attachments and User Content', body: 'Users may upload photographs, videos, documents, and other permitted files where supported. Users must have the right to upload the material and must not upload malware, illegal content, confidential third-party information without authorization, or misleading evidence. FarmEazy may remove or restrict content that violates platform rules or applicable law. Access to private attachments is authorization-controlled.' },
      { title: '13. AI and Support', body: 'FarmEazy may provide an AI support assistant to answer general platform questions and guide users. AI responses may be incomplete or incorrect and must not be treated as professional legal, medical, veterinary, financial, or safety advice. Account-specific actions, payment disputes, security concerns, complaints, and other sensitive matters may be escalated to human support. Chat history may be retained to provide continuity and support.' },
      { title: '14. Prohibited Conduct', body: 'Users must not commit fraud, impersonation, unauthorized access, payment manipulation, coupon abuse, coin abuse, review manipulation, harassment, unlawful discrimination, malware distribution, scraping that violates platform controls, listing manipulation, or attempts to defeat security, availability, capacity, or authorization mechanisms.' },
      { title: '15. Privacy and Data Handling', body: 'FarmEazy processes account, transaction, location, farm, crop, marketplace, support, and device information as described in the Privacy Policy and as required to operate the platform. Users should avoid submitting unnecessary sensitive information in listings, chats, attachments, or notes.' },
      { title: '16. Third-Party Services', body: 'FarmEazy may integrate payment gateways, cloud storage, maps, messaging, analytics, identity providers, delivery providers, and other third-party services. Their availability and processing are subject to their respective terms and technical limitations. FarmEazy does not represent that every third-party service will always be available.' },
      { title: '17. Marketplace Disclaimer', body: 'Except where FarmEazy expressly acts as the seller or provider, FarmEazy primarily facilitates connections and platform workflows between users. Users should independently verify material product, livestock, equipment, service, safety, ownership, regulatory, and quality information before completing a transaction.' },
      { title: '18. Suspension and Termination', body: 'FarmEazy may restrict, suspend, or terminate access where reasonably necessary for security, fraud prevention, legal compliance, abuse prevention, unresolved payment issues, or material violation of these Terms. Transaction records may be retained where necessary for legal, accounting, security, or dispute purposes.' },
      { title: '19. Changes to These Terms', body: 'FarmEazy may update these Terms when the platform, legal requirements, integrations, or business rules change. Where a new version requires renewed consent, users may be asked to accept the updated version before continuing to use affected features.' },
      { title: '20. Governing Law and Contact', body: 'These Terms are intended to operate subject to applicable laws and regulations. Nothing in these Terms removes any mandatory consumer, animal-welfare, safety, taxation, or other statutory rights that cannot lawfully be excluded. For questions about these Terms, users should contact FarmEazy through the official support/contact channels published on the platform.' },
    ]}
  />
)

export default Terms
